apiVersion: v1
kind: Service
metadata:
  name: http-canary-service
  labels: 
    category: microservices
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  # the set of pods to load balance traffic to.
  selector:
    app: http-canary
  type: NodePort
